services:
  demoname-backend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: imagename-backend:latest
    env_file:
      - ./backend/.env
    volumes:
      - ~/.aws/credentials:/root/.aws/credentials:ro
      - ~/.aws/config:/root/.aws/config:ro
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw
    ports:
      - "8000:8000"
    restart: always
    container_name: demoname-backend
  demoname-frontend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: imagename-frontend:latest
    env_file:
      - ./frontend/.env.local
    ports:
      - "3000:8080"
    restart: always
    container_name: demoname-frontend